### ISSUE TITLE
Raw string rendering

### ISSUE THREAD

**Issue by tshort** [yurivish/Hyperscript.jl#14]
I need to output un-encoded strings that include raw HTML. This is easy enough to implement externally:

```julia
struct Raw
    str::String
end
Base.show(io::IO, m::MIME"text/html", rawstr::Raw) = print(io, rawstr.str)
```

Example:

```julia
julia> m("div", Raw("<span>hi</span>"))
<div><span>hi</span></div>
```
Is there any interest in having this in Hyperscript?

**Comment by yurivish** [comment]
I was going to mention `@tags_noescape`, and `m(Hyperscript.NOESCAPE_HTMLSVG_CONTEXT, "div", "<span>hi</span>"), but doesn't your last PR actually solve this for us? 

```julia
julia> @tags div

julia> div(HTML("<span>hi</span>"))
<div><span>hi</span></div>
```

**Comment by tshort** [comment]
Nice! Thanks, @yurivish.

**Comment by tshort** [comment]
Thanks also for the reminder on `@tags_noescape`. That will be helpful for me in another scenario.
