### ISSUE TITLE
Invalid call to validateattrs

### ISSUE THREAD

**Issue by kskyten** [yurivish/Hyperscript.jl#15]
Running
```julia
using Hyperscript
m("div")
```
raises the following error on the current version in the package registry:
```julia
ERROR: MethodError: no method matching validateattrs(::Hyperscript.Validate{true}, ::String, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}})
Closest candidates are:
validateattrs(::Hyperscript.Validate, ::Any, ::NamedTuple) at ~/.julia/packages/Hyperscript/qO5ub/src/Hyperscript.jl:80
validateattrs(::Hyperscript.NoValidate, ::Any, ::NamedTuple) at ~/.julia/packages/Hyperscript/qO5ub/src/Hyperscript.jl:94
Stacktrace:
[1] Hyperscript.Node(::Hyperscript.Validate{true}, ::String, ::Tuple{}, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at ~/.julia/packages/Hyperscript/qO5ub/src/Hyperscript.jl:111
[2] #m#7(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::String) at ~/.julia/packages/Hyperscript/qO5ub/src/Hyperscript.jl:174
[3] m(::String) at ~/.julia/packages/Hyperscript/qO5ub/src/Hyperscript.jl:174
[4] top-level scope at none:0

```

**Comment by yurivish** [comment]
Hi, can you see if this happens using the master branch? It may be that the latest version just wants a proper release — I haven’t made one since Julia 1.0, I think.

**Comment by kskyten** [comment]
Seems to be working in master.

**Comment by SimonDanisch** [comment]
Yes, can we make a new release? :) We're at ` 375 commits to master since this release ` ;)

**Comment by yurivish** [comment]
Poke me in a few weeks when I have a little more time — we should make a new release. :)

**Comment by SimonDanisch** [comment]
To you want to transfer it to an org we both have access to? I could make a release, if you want

**Comment by yurivish** [comment]
I just added you as a collaborator to this repository. Does that give you adequate permissions to make a release?

**Comment by SimonDanisch** [comment]
Let's try ;)

**Comment by yurivish** [comment]
Thanks for the release. I'm closing this issue now since the fix has been deployed.
