### ISSUE TITLE
Adding attributes without values

### ISSUE THREAD

**Issue by kskyten** [yurivish/Hyperscript.jl#16]
How do I add, for example, a `controls` attribute to a video tag?
```html
<video controls>
  <source src="movie.mp4" type="video/mp4">
  <source src="movie.ogg" type="video/ogg">
  Your browser does not support the video tag.
</video>
```

**Comment by yurivish** [comment]
Hi,

You can use `nothing` as the value to create a valueless attribute: `m("video", controls=nothing)`.

Note that right now I recommend using the master branch of Hyperscript; now that it's got more users I plan to do a release some time in the near future with all of the latest improvements.

**Comment by kskyten** [comment]
Thanks!
