### ISSUE TITLE
Thoughts about a templating language?

### ISSUE THREAD

**Issue by fonsp** [yurivish/Hyperscript.jl#21]
This is awesome! I look forward to play with it more! One of my favorite features is that you can use objects from other packages inside of it, and it will call the `repr(MIME"text/html"(), x)` function - this makes it super useful for composing UI. I think that [Pluto.jl](https://github.com/fonsp/Pluto.jl) + Hyperscript.jl + https://pluto-on-binder.glitch.me/ has amazing potential

Just a quick question: I was thinking about the option to turn this into a HTML templating library for Julia - like https://github.com/developit/htm or https://github.com/observablehq/stdlib#html. Have you experimented with this? 

Would it be useful? The current syntax is already quite easy and concise, but maybe it would be easier for people who know HTML, or if you want to copy paste some HTML.

**Comment by fonsp** [comment]
Also I would love to chat sometime! I love your work, and it seems like we have similar interests!

fonsvdplas@gmail.com

**Comment by Moelf** [comment]
does https://github.com/jverzani/Mustache.jl qualify as a templating library?

**Comment by fonsp** [comment]
Oh that looks cool! But not exactly what I had in mind. I guess I mean something like:

(pseudocode)

```julia
my_box(content) = hmt"
<div id=$( random_string() )>
	$(content)
</div>
"

md_app() = htm"
<body>
	$(map([1,2,3]) do n
		content("$n fast $n furious")
	end)
</body>
"
```

**Comment by yurivish** [comment]
Hi Fons, I agree, a string template literal would be a very useful way to write HTML in Julia. It’s a bit of a heavier dependency, but one way to try this out could be to use Gumbo (https://github.com/JuliaWeb/Gumbo.jl) and walk the tree structure it creates to lower it to Hyperscript nodes.

Happy to chat sometime! I’m a bit busy this week, but I’d be glad to chat sometime next week. Neat to see Grant Sanderson taking advantage of Pluto’s reactivity - I’ve been following along the lectures.

**Comment by SimonDanisch** [comment]
Btw, I've been thinking for some time to switch Gumbo to use Hyperscript ;) That'd be pretty neat for various reasons, I think!

**Comment by clarkevans** [comment]
@fonsp So, I think you might be looking for something like [lit-html](https://lit-html.polymer-project.org/)?  It could be done as a macro (wrapping Symbols in the parse tree with html_escape call), so you could write your logic in Julia, but use strings rather than making a server-side DOM. Anyway, it's separate from `Hyperscript`.

**Comment by clarkevans** [comment]
I'd love something like the `HTL` package; it could be built on top of `Hyperscript` and `Gumbo`?

**Comment by fonsp** [comment]
@dralletje said that he wrote this! Can't find his code though

**Comment by dralletje** [comment]
Yes

https://gist.github.com/dralletje/c9772c35dcb542325b24c9609c643c23

**Comment by clarkevans** [comment]
Hi.  So, I've made progress using Michiel Dral's prototype as a basis.  The design of [HypertextLiteral.jl](https://github.com/clarkevans/HypertextLiteral.jl) doesn't parse to `Hyperscript.jl` objects though, it parses to an `HTL` object which is an array of strings (treated as previously-escaped HTML) and various objects that are to be escaped at runtime.  Hyperscript objects work lovely in that context.

**Comment by schneiderfelipe** [comment]
Hi, I've been working on [HTM.jl](https://github.com/schneiderfelipe/HTM.jl), a small (<300 lines) library that is backend-agnostic (compiles to `create_element` calls [just like `htm`](https://github.com/developit/htm#advanced-usage)) but generates Hyperscript objects by default:

```julia
julia> using HTM

julia> my_box(content) = htm"
           <div id=$(rand(1:100))>
               $(content)
           </div>"
my_box (generic function with 1 method)

julia> my_app() = htm"""
           <body>
               $(map([1,2,3]) do n
                   my_box("$n fast $n furious")
               end)
           </body>"""
my_app (generic function with 1 method)

julia> app = my_app()
<body>
    <div id="27">
        1 fast 1 furious
    </div>
    <div id="1">
        2 fast 2 furious
    </div>
    <div id="14">
        3 fast 3 furious
    </div>
</body>

julia> typeof(app)  # Hyperscript object!
Hyperscript.Node{Hyperscript.HTMLSVG}
```

**Comment by clarkevans** [comment]
@schneiderfelipe Sounds lovely.  You're aware of [HypertextLiteral.jl](https://github.com/MechanicalRabbit/HypertextLiteral.jl)?  

There is an advantage to generating Hyperscript objects: you could then work with them as a server-side DOM.  For example, one could then create a React like system that could calculate the differences between two rendered pages, and send a "patch" to the client.  Conversely, you will pay about 10x or more performance penalty over HypertextLiteral to render to an intermediate DOM. For small documents it won't matter, but, for even modestly large pages or reports, it becomes very substantial.

**Comment by schneiderfelipe** [comment]
@clarkevans Yes, I've seen [your presentation at PlutoCon](https://www.youtube.com/watch?v=5E21bdnAzYI)--very nice. Both packages overlap; my main goal is to have something backend-agnostic that would feel like using `@md_str`.

The React idea is exciting. HTM.jl may already work with the Julia server-side ecosystem. A (re)definition of `create_element` could use [`WebIO.jl`](https://github.com/JuliaGizmos/WebIO.jl), for instance,

```julia
julia> using HTM, WebIO

julia> HTM.create_element(type, props, children...) = WebIO.Node(type, children, props)  # !

julia> x = htm"<div id=$(rand(1:100)) />"
(div
  ((),)
  Dict{String, Any}("id" => 37))

julia> dump(x, maxdepth=1)
Node{WebIO.DOM}
  instanceof: WebIO.DOM
  children: FunctionalCollections.PersistentVector{Any}
  props: Dict{Symbol, Any}
```

(I haven't tested further, but WebIO.jl supports [displaying to frontends (Blink.jl, Mux.jl, etc.)](https://juliagizmos.github.io/WebIO.jl/latest/gettingstarted/#Displaying-to-a-Frontend), and [communication between Julia and JavaScript](https://juliagizmos.github.io/WebIO.jl/latest/gettingstarted/#Communicating-between-Julia-and-JavaScript). So having a backend-agnostic solution might be very useful.)

> I looked a bit at your implementation. I think mbostock's API wraps plural elements in an implicit `div`. This might be better than returning a tuple in the case where you've got more than one top-level tag. I'm pretty sure mbostok's implementation wraps bare strings in an implicit `span`.

Yes, that was a design decision. mbostok's implementation [wraps in `span`, and provides `DocumentFragment`](https://github.com/observablehq/htl#features). I didn't quite like the idea of silently creating a new element, so I opted to follow `htm` and [return an iterable](https://github.com/developit/htm#advanced-usage). This might be surprising, but I'm pleased with the Hyperscript.jl output, which makes it very explicit:

```julia
julia> using HTM

julia> htm"<div /><div />"
(<div></div>, <div></div>)
```

I'm open to suggestions 😊

**Comment by clarkevans** [comment]
> Both packages overlap; my main goal is to have something backend-agnostic that would feel like using `@md_str`.

At this time, `HypertextLiteral` doesn't export `@htl_str` but I should probably do that now that there seems to be a use case that `@htl` doesn't provide (see the talk).  In this way, it already works similar to `@md_str`, yea?

```
julia> using HypertextLiteral: @htl_str
julia> display("text/html", htl"<div id=$(rand(1:100))/>")
<div id='95'/>
```



> (I haven't tested further, but WebIO.jl supports [displaying to frontends (Blink.jl, Mux.jl, etc.)](https://juliagizmos.github.io/WebIO.jl/latest/gettingstarted/#Displaying-to-a-Frontend), and [communication between Julia and JavaScript](https://juliagizmos.github.io/WebIO.jl/latest/gettingstarted/#Communicating-between-Julia-and-JavaScript). So having a backend-agnostic solution might be very useful.)

Oh.  I wasn't aware of `WebIO`.  But yea, a server-side `React` like ecosystem could be quite nice for making user interface components.  The string-based approach used by `HypertextLiteral` is ill-suited towards DOM style manipulation.
