### ISSUE TITLE
Fails to build on 1.6: type piracy?

### ISSUE THREAD

**Issue by timholy** [yurivish/Hyperscript.jl#24]
Hyperscript doesn't build on nightly. The reason is https://github.com/yurivish/Hyperscript.jl/blob/7731aecafd06e9366020ebee0d6674527fe3d7d6/src/Hyperscript.jl#L117

Here's why: 1.6 has a new TOML parser that includes [this line](https://github.com/JuliaLang/julia/blob/15e1d592ef034725949452280a39c71df4f946f9/base/toml_parser.jl#L676). The issue is that `Union{} <: Hyperscript.AbstractNode`, because `Union{}` is a subtype of every other type, and hence instead of creating an [array](https://github.com/JuliaLang/julia/blob/15e1d592ef034725949452280a39c71df4f946f9/base/array.jl#L405-L411) with eltype `Union{}` it tries (during package loading!) to call `Union{}(xs...)`, which obviously fails. CC @KristofferC.

I am pretty sure this method counts as type-piracy (even if you own `YourType`, you do not own `Vector{YourType}`), so I guess the question is, can it be eliminated?

**Comment by KristofferC** [comment]
I guess it could be written as `Vector{Union}()` but changing the result of `Union{}[]` is probably not ideal anyway.

**Comment by timholy** [comment]
In case someone asks:
```julia
julia> using SnoopCompileCore

julia> abstract type AbstractNode{T} end

julia> invs = @snoopr Base.getindex(node::Type{<:AbstractNode}, xs::Any...) = node(xs...);

julia> using SnoopCompile

julia> length(uinvalidated(invs))
358
```
All the invalidated methods are callers of `parse_array`. But if you load Revise it goes up to 590.

**Comment by timholy** [comment]
Hmm, tests pass just fine with
```diff
diff --git a/src/Hyperscript.jl b/src/Hyperscript.jl
index 10ca312..8608159 100644
--- a/src/Hyperscript.jl
+++ b/src/Hyperscript.jl
@@ -114,7 +114,8 @@ function Base.typed_hvcat(node::AbstractNode, rows::Tuple{Vararg{Int64}}, xs::An
 end
 Base.typed_hcat(node::AbstractNode, xs::Any...) = node(xs...)
 Base.typed_vcat(node::AbstractNode, xs::Any...) = node(xs...)
-Base.getindex(node::Union{AbstractNode, Type{<:AbstractNode}}, xs::Any...) = node(xs...)
+Base.getindex(node::AbstractNode, xs::Any...) = node(xs...)
+# Base.getindex(node::Union{AbstractNode, Type{<:AbstractNode}}, xs::Any...) = node(xs...)
 
 function Base.:(==)(x::Node, y::Node)
     context(x)  == context(y)  && tag(x)   == tag(y) &&
```

**Comment by SimonDanisch** [comment]
@yurivish does anything speak against tagging a new version with your fix?

**Comment by timholy** [comment]
Meanwhile I think this can be closed. Thanks @yurivish, sorry I didn't notice the fix when it came in.

**Comment by yurivish** [comment]
@SimonDanisch Not at all, feel free to tag a new version!
