### ISSUE TITLE
flat should accept AbstractArray

### ISSUE THREAD

**Issue by schneiderfelipe** [yurivish/Hyperscript.jl#30]
I think only accepting `Array` in
https://github.com/yurivish/Hyperscript.jl/blob/1fc13cc7cb78ec1f93c1919b80e1a1ad27a9948e/src/Hyperscript.jl#L133
is too strict.

It leads to the following surprising behavior:

```julia
julia> using Hyperscript

julia> let children = [1, 2, 3]  # Array
           m("div", children)
       end
<div>123</div>

julia> using StaticArrays

julia> let children = @SVector Int[1, 2, 3]  # not Array, but AbstractArray
           m("div", children)
       end
<div>&#91;1, 2, 3&#93;</div>
```

**Comment by yurivish** [comment]
Hi, I think that makes sense. Would you mind submitting a PR?
