### ISSUE TITLE
Pretty rendering

### ISSUE THREAD

**Issue by tshort** [yurivish/Hyperscript.jl#4]
It'd be nice to have an option to pretty-print the html renders and indent to reflect level.

**Comment by yurivish** [comment]
Agreed. It hasn't been a priority yet, but @ninjin also thought it would be nice.

Conveniently, the context design pattern makes it possible to add as a CSS/DOM-specific setting:

```julia
struct CSS <: Context
    allow_nan_attr_values::Bool
end

struct DOM <: Context
    allow_nan_attr_values::Bool
    noescape::Bool
end
```

**Comment by yurivish** [comment]
And now there _is_ pretty rendering. Thanks, @tshort!
