### ISSUE TITLE
Odd error with include

### ISSUE THREAD

**Issue by tshort** [yurivish/Hyperscript.jl#7]
I'm not sure if this is a Julia bug or if my system is messed up. The following syntax is causing an error. It works in the REPL but not with `include`. Package tests work fine.

```julia
shell> cat bug.jl
div."a"("hello")

julia> include("bug.jl")
ERROR: LoadError: syntax: malformed expression
Stacktrace:
 [1] include at ./boot.jl:314 [inlined]
 [2] include_relative(::Module, ::String) at ./loading.jl:1067
 [3] include(::Module, ::String) at ./sysimg.jl:29
 [4] include(::String) at ./sysimg.jl:68
 [5] top-level scope
in expression starting at /home/tshort/FS/appfiles/julia/MDPad/bug.jl:1

julia> div."a"("hello")
<div class="a">hello</div>
```

**Comment by yurivish** [comment]
Interesting. I just updated my Julia installation to the latest master and see the same behavior. I suspect this is a Julia bug.

I can replicate it here with 

```julia
# bug.jl
using Hyperscript
@tags div
div."a"("hello")
```

and also with simply `div."a"` in bug.jl once the first two lines have been evaluated at the REPL.  `div.a` without quotes is fine.

**Comment by yurivish** [comment]
The simplest case is placing the following in a file and including it at the REPL to see the "malformed expression" error (no Hyperscript involved):

```
f."x"
```

versus at the REPL:

```julia
julia> f."x"
ERROR: UndefVarError: f not defined
```

**Comment by tshort** [comment]
Issue filed with Julia...

**Comment by tshort** [comment]
Looks like this is fixed on Julia master, courtesy of Jeff.
